In [ ]:
import numpy as np

print("===================================")
print("      MATRIX OPERATIONS TOOL")
print("===================================")

# Input matrix size
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

print("\nEnter elements of Matrix A:")
A = np.array([[float(input(f"A[{i}][{j}] = ")) for j in range(cols)] for i in range(rows)])

print("\nEnter elements of Matrix B:")
B = np.array([[float(input(f"B[{i}][{j}] = ")) for j in range(cols)] for i in range(rows)])

while True:
    print("\n========== MENU ==========")
    print("1. Matrix Addition")
    print("2. Matrix Subtraction")
    print("3. Matrix Multiplication")
    print("4. Transpose of Matrix A")
    print("5. Determinant of Matrix A")
    print("6. Exit")

    choice = int(input("Enter your choice: "))

    if choice == 1:
        print("\nMatrix A:")
        print(A)
        print("\nMatrix B:")
        print(B)
        print("\nAddition Result:")
        print(A + B)

    elif choice == 2:
        print("\nSubtraction Result:")
        print(A - B)

    elif choice == 3:
        if cols == rows:
            print("\nMultiplication Result:")
            print(np.dot(A, B))
        else:
            print("\nMatrix multiplication requires compatible dimensions.")

    elif choice == 4:
        print("\nTranspose of Matrix A:")
        print(A.T)

    elif choice == 5:
        if rows == cols:
            print("\nDeterminant of Matrix A:")
            print(np.linalg.det(A))
        else:
            print("\nDeterminant can only be calculated for a square matrix.")

    elif choice == 6:
        print("\nThank you for using Matrix Operations Tool.")
        break

    else:
        print("\nInvalid Choice! Please try again.")

      MATRIX OPERATIONS TOOL
Enter number of rows: 3
Enter number of columns: 3

Enter elements of Matrix A:
A[0][0] = 123445678
A[0][1] = 6
A[0][2] = 8
A[1][0] = 7
A[1][1] = 3
A[1][2] = 6
A[2][0] = 9
A[2][1] = 5
A[2][2] = 9

Enter elements of Matrix B:
B[0][0] = 4
B[0][1] = 0
B[0][2] = 9
B[1][0] = 7
B[1][1] = 6
B[1][2] = 5
B[2][0] = 4
B[2][1] = 6
B[2][2] = 8

========== MENU ==========
1. Matrix Addition
2. Matrix Subtraction
3. Matrix Multiplication
4. Transpose of Matrix A
5. Determinant of Matrix A
6. Exit
Enter your choice: 1

Matrix A:
[[1.23445678e+08 6.00000000e+00 8.00000000e+00]
 [7.00000000e+00 3.00000000e+00 6.00000000e+00]
 [9.00000000e+00 5.00000000e+00 9.00000000e+00]]

Matrix B:
[[4. 0. 9.]
 [7. 6. 5.]
 [4. 6. 8.]]

Addition Result:
[[1.23445682e+08 6.00000000e+00 1.70000000e+01]
 [1.40000000e+01 9.00000000e+00 1.10000000e+01]
 [1.30000000e+01 1.10000000e+01 1.70000000e+01]]

========== MENU ==========
1. Matrix Addition
2. Matrix Subtraction
3. Matrix Multiplication
4.